pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        DOCKER_IMAGE_TAG = "my-app-challenge:build-${env.BUILD_ID}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "Build docker image"
            }
        }
        stage('Make Container') {
            steps {
                sh "docker build -t jenkinsci/blueocean:${env.BUILD_ID} ."
                sh "docker tag jenkinsci/blueocean:${env.BUILD_ID} jenkinsci/blueocean:latest"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
